language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"

before_install:
    - npm install
    - npm install -g cordova
    - npm install -g ionic
    - npm install -g protractor
    - npm start:
        background: true
    - sleep 5
  override:
    - cd test
    - webdriver-manager update
#    - ionic serve --address localhost
    - protractor protractor.config.js