language: node_js
node_js:
  - '0.10.33'
before_script:
  - pwd
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g ionic'
  - 'bower install' # install bower packages

  - pwd
  - ls -alh /home/travis/build/stevelyall/project-ernie-app/www/lib/ionic/js/angular
  - ls -alh /home/travis/build/stevelyall/project-ernie-app/www/lib/ionic/js
  - cat /home/travis/build/stevelyall/project-ernie-app/www/lib/ionic/js/angular/angular.js
after_script: