language: node_js
node_js:
  - '0.10.33'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

  - 'npm install -g bower grunt-cli jshint phantomjs'
  - 'npm install karma-jasmine -g'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages
  - npm list -g


after_script: