language: node_js
node_js:
  - '0.10.33'
before_script:
  - pwd
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - pwd
  - ls
  - ls node_modules
  - 'npm install' # install npm packages
  - ls node_modules
  - 'npm install -g bower grunt-cli jshint phantomjs karma karma-jasmine karma-phantomjs-launcher --save-dev'
  - ls node_modules
  - 'bower install' # install bower packages
  #- karma start test/karma.conf.js


after_script:
