language: node_js
node_js:
  - '0.10.33'
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma-jasmine grunt-cli jshint'
  - 'npm install -g phantomjs'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages


after_script:
 - 'karma'