language: node_js
node_js:
  - '0.10.33'
before_script:
  - pwd
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install ionic'
  #- 'bower install' # install bower packages

after_script: